# Buscaminas game

This is a jupyter notebook for help me to developing a buscaminas game. Next up the set of rules you need to Know to play buscaminas:

## Buscaminas Rules

- The goal of the game is to uncover all the squares that do not contain mines.

- The board contains hidden mines in some squares.

- Each uncovered square shows a number:

- The number indicates how many mines are in the 8 surrounding squares.

- If the square contains a mine, you lose the game.

- You can mark a square with a flag if you suspect it contains a mine.

- If you uncover a square with no mine and the number 0, all adjacent squares are automatically uncovered.

The game ends when:

1. Victory: all non-mine squares have been uncovered.

1. Defeat: you uncover a square that contains a mine. 

In [25]:
import random
import numpy as np

First of all we define board size and how many bob there will be.

In [27]:
rows = 8
columns = 8
mines = 10

In [28]:
board =  np.zeros((rows, columns), dtype=int)

Let's create a method to fill the board randomly

In [29]:
def random_board_fill(board,mines):
    rows, columns = board.shape
    positions = random.sample(range(rows * columns), mines)
    for pos in positions:
        row , col = divmod(pos, columns)
        board[row][col] = -1
    
    return board

board = random_board_fill(board, mines)
print(board)

[[ 0 -1  0 -1  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0 -1 -1  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0  0  0]]


Next step, Count how many mines there are around each cell

In [30]:
def compute_board_numbers(board):
    rows, columns = board.shape
    for i in range(rows):
        for j in range(columns):
            if board[i][j] == -1:
                continue

            count = 0
            for x in range(max(0, i-1), min(i + 2 , rows)):
                for y in range(max(0, j-1), min(j + 2, columns)):
                    if board[x][y] == -1:
                        count += 1
            board[i][j] = count
    return board

board =  compute_board_numbers(board)
print(board)

[[ 1 -1  2 -1  1  1  1  1]
 [ 2  3  4  2  1  1 -1  1]
 [ 2 -1 -1  1  0  1  1  1]
 [-1  3  2  1  0  0  1  1]
 [ 1  1  0  0  0  0  2 -1]
 [ 0  0  0  0  1  1  3 -1]
 [ 0  0  0  1  2 -1  2  1]
 [ 0  0  0  1 -1  2  1  0]]


Next function builds board's display 

In [31]:
def display_board(board, visible):
    rows, columns = board.shape
    for i in range(rows):
        row = ""
        for j in range(columns):
            if visible[i][j]:
                row += str(board[i][j]) + " "
            else:
                row += "# "
        print(row)

visible =  np.full((rows, columns), False)
display_board(board, visible)

# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 


Now a function to show the cell selected by the player

In [32]:
def show_cell(board, visible, row, column):
    if visible[row][column]:
        return
    visible[row][column] = True
    if board[row][column] == 0:
        rows, columns = board.shape
        for x in range(max(0,row - 1), min(row + 2 , rows)):
            for y in range(max(0, column - 1), min(column + 2 , columns)):
                if not visible[x][y]:
                    show_cell(board, visible, x, y)

We have writen all the functions we need to develope this game, then it time to write code for game cycle.

In [33]:
'''Funnctions to play buscaminas'''
print("Enter coordinates for the next move:")
move_x = int(input("x: "))
print(f"This is your input for x: {move_x}")
move_y = int(input("Enter your input for y: "))
print(f"This is your input for y: {move_y}")

Enter coordinates for the next move:
This is your input for x: 5
This is your input for y: 4


## Next up some information to build our buscaminas

In [34]:
game_board = np.zeros((rows, columns), dtype=int)
game_board = random_board_fill(game_board, 10)
game_board = compute_board_numbers(game_board)
print(game_board)
game_state_display = np.full((rows, columns), False)
#display_board(game_board, game_state_display)


[[ 0  1  1  2 -1  2 -1 -1]
 [ 1  2 -1  2  1  2  2  2]
 [ 1 -1  2  1  0  0  0  0]
 [ 2  3  3  2  1  0  0  0]
 [-1  3 -1 -1  1  0  1  1]
 [ 2 -1  3  2  1  0  1 -1]
 [ 1  1  1  0  0  0  1  1]
 [ 0  0  0  0  0  0  0  0]]


In [36]:
def is_a_win(visible):
    for i, col in enumerate(visible):
        for n in col:
            if not n:
                return False
    return True

print(is_a_win(game_state_display))

False


In [ ]:
while(True):
    display_board(game_board, game_state_display)
    print(" ")
    x = int(input("x: "))
    y = int(input("y: "))
    if game_board[x][y] == -1:
        print("You hit a bom, you loose")
        break
    if is_a_win(game_state_display):
        print("You Win!!")
        break



# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
 
 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
# # -1 # # # # # 
# # # # # # # # 
# # # # # # # # 
# # # # # # # # 
 
