# Buscaminas game

This is a jupyter notebook for help me to developing a buscaminas game. Next up the set of rules you need to Know to play buscaminas:

## Buscaminas Rules

- The goal of the game is to uncover all the squares that do not contain mines.

- The board contains hidden mines in some squares.

- Each uncovered square shows a number:

- The number indicates how many mines are in the 8 surrounding squares.

- If the square contains a mine, you lose the game.

- You can mark a square with a flag if you suspect it contains a mine.

- If you uncover a square with no mine and the number 0, all adjacent squares are automatically uncovered.

The game ends when:

1. Victory: all non-mine squares have been uncovered.

1. Defeat: you uncover a square that contains a mine. 

In [3]:
import random
import numpy as np

First of all we define board size and how many bob there will be.

In [1]:
rows = 8
columns = 8
mines = 10

In [4]:
board =  np.zeros((rows, columns), dtype=int)

Let's create a method to fill the board randomly

In [7]:
def random_board_fill(board,mines):
    rows, columns = board.shape
    positions = random.sample(range(rows * columns), mines)
    for pos in positions:
        row , col = divmod(pos, columns)
        board[row][col] = -1
    
    return board

board = random_board_fill(board, mines)
print(board)

[[-1  0 -1  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1]
 [ 0 -1  0  0  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0 -1  0  0  0  0]
 [ 0 -1  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0 -1]]
